import { createWeaponProfileRegistry } from '../../engine/equipment/WeaponProfile.js';

export const weaponProfiles = createWeaponProfileRegistry([
  {
    id: 'unarmed',
    displayName: 'Unarmed',
    description: 'Bare hands. Fast, desperate, and short-ranged.',
    weaponType: 'unarmed',
    damage: 10,
    attackRange: 2.25,
    attackCooldown: 0.74,
    windupTime: 0.05,
    recoveryTime: 0.2,
    staminaCost: 3,
    hitReactionType: 'light_stagger',
    tags: ['starting', 'melee', 'fallback'],
  },
  {
    id: 'wood_axe',
    displayName: 'Wood Axe',
    description: 'A plain chopping axe. Better at redwoods than swordplay.',
    weaponType: 'axe',
    damage: 13,
    attackRange: 2.65,
    attackCooldown: 1.1,
    windupTime: 0.14,
    recoveryTime: 0.38,
    staminaCost: 4,
    hitReactionType: 'heavy_stagger',
    tags: ['weapon', 'tool', 'melee', 'axe', 'woodcutting', 'field-survival'],
  },
  {
    id: 'fishing_rod',
    displayName: 'Rod A1',
    description: 'The canonical Kerovac Expo A1 reed pole, now rigged for casting.',
    weaponType: 'tool',
    damage: 2, attackRange: 2.0, attackCooldown: 1.2, windupTime: 0.1, recoveryTime: 0.2, staminaCost: 1, hitReactionType: 'light_stagger',
    tags: ['weapon', 'tool', 'fishing', 'field-survival'],
  },
  {
    id: 'rusted_sword',
    displayName: 'Broadsword',
    description: 'The ritual broadsword recovered from the old temple. It keeps the old sword balance but now appears as a 3D first-person blade.',
    weaponType: 'sword',
    damage: 17,
    attackRange: 3.05,
    attackCooldown: 1.05,
    windupTime: 0.12,
    recoveryTime: 0.34,
    staminaCost: 4,
    hitReactionType: 'slash_stagger',
    tags: ['weapon', 'melee', 'blade', 'black_grass_temple'],
  },
]);
