import { createWeaponProfileRegistry } from '../../engine/equipment/WeaponProfile.js';

export const weaponProfiles = createWeaponProfileRegistry([
  {
    id: 'unarmed',
    displayName: 'Unarmed',
    description: 'Bare hands. Fast, desperate, and short-ranged.',
    weaponType: 'unarmed',
    damage: 10,
    attackRange: 2.25,
    attackCooldown: 0.74,
    windupTime: 0.05,
    recoveryTime: 0.2,
    staminaCost: 3,
    hitReactionType: 'light_stagger',
    tags: ['starting', 'melee', 'fallback'],
  },
  {
    id: 'wood_axe',
    displayName: 'Wood Axe',
    description: 'A plain chopping axe. Better at redwoods than swordplay.',
    weaponType: 'axe',
    damage: 13,
    attackRange: 2.65,
    attackCooldown: 1.1,
    windupTime: 0.14,
    recoveryTime: 0.38,
    staminaCost: 4,
    hitReactionType: 'heavy_stagger',
    tags: ['weapon', 'tool', 'melee', 'axe', 'woodcutting', 'field-survival'],
  },
  {
    id: 'fishing_rod',
    displayName: 'Rod A1',
    description: 'The canonical Kerovac Expo A1 reed pole, now rigged for casting.',
    weaponType: 'tool',
    damage: 2, attackRange: 2.0, attackCooldown: 1.2, windupTime: 0.1, recoveryTime: 0.2, staminaCost: 1, hitReactionType: 'light_stagger',
    tags: ['weapon', 'tool', 'fishing', 'field-survival'],
  },
  {
    id: 'dreadstone_sword',
    displayName: 'Dreadstone Sword',
    description: 'A long, balanced blade controlled directly in world space.',
    weaponType: 'sword',
    damage: 16,
    attackRange: 3.0,
    attackCooldown: 0.92,
    windupTime: 0.08,
    recoveryTime: 0.28,
    staminaCost: 4,
    hitReactionType: 'heavy_stagger',
    tags: ['weapon', 'melee', 'sword', 'physical-melee', 'field-survival'],
  }
]);
