// Canonical fish species selected from the Kerovac Expo fish variant grid.
//
// These entries intentionally mirror the existing Expo display definitions and
// DungeonGeometryBuilder fish template inputs. Keep the geometry/material fields
// stable so future fishing gameplay can instantiate the selected species without
// regenerating or redesigning their visuals.

export const SELECTED_KEEPER_FISH_LABELS = Object.freeze(['C1', 'C2', 'C4', 'D2', 'D3']);

export const FISH_SPECIES_REGISTRY = Object.freeze({
  fish_species_c1: Object.freeze({
    id: 'fish_species_c1',
    displayName: 'Small River Fish',
    sourceSelectionLabel: 'C1',
    sourceExpoPrimitiveId: 'K_expo_fish_C1_small_river',
    sourceItemId: 'smallRiverFish',
    sourceVariant: 'smallRiverFish',
    constructionTemplate: 'single-reusable-symmetrical-volumetric-template',
    bodyGeometryStyle: 'closedEllipsoidBody',
    bodyMaterial: 'fishScaleSilver',
    finMaterial: 'fishFinAmber',
    eyeMaterial: 'tinyBlackEye',
    bodyLength: 1.25,
    bodyHeight: 0.3,
    bodyWidth: 0.22,
    tailScale: 0.92,
    dorsalScale: 0.82,
    pectoralScale: 0.86,
    headTaper: 1,
    scale: 1,
  }),
  fish_species_c2: Object.freeze({
    id: 'fish_species_c2',
    displayName: 'Broad Carp Fish',
    sourceSelectionLabel: 'C2',
    sourceExpoPrimitiveId: 'K_expo_fish_C2_broad_carp',
    sourceItemId: 'broadCarpFish',
    sourceVariant: 'broadCarpFish',
    constructionTemplate: 'single-reusable-symmetrical-volumetric-template',
    bodyGeometryStyle: 'closedEllipsoidBody',
    bodyMaterial: 'fishScaleKoiCreamOrange',
    finMaterial: 'fishFinAmber',
    eyeMaterial: 'tinyBlackEye',
    bodyLength: 1.55,
    bodyHeight: 0.58,
    bodyWidth: 0.36,
    tailScale: 1.18,
    dorsalScale: 1.06,
    pectoralScale: 1.0,
    headTaper: 1,
    scale: 1,
  }),
  fish_species_c4: Object.freeze({
    id: 'fish_species_c4',
    displayName: 'Spine Back Fish',
    sourceSelectionLabel: 'C4',
    sourceExpoPrimitiveId: 'K_expo_fish_C4_spine_back',
    sourceItemId: 'spineBackFish',
    sourceVariant: 'spineBackFish',
    constructionTemplate: 'single-reusable-symmetrical-volumetric-template',
    bodyGeometryStyle: 'closedEllipsoidBody',
    bodyMaterial: 'fishScaleZebraOlive',
    finMaterial: 'fishFinDark',
    eyeMaterial: 'tinyBlackEye',
    bodyLength: 1.6,
    bodyHeight: 0.38,
    bodyWidth: 0.26,
    tailScale: 1.0,
    dorsalScale: 1.38,
    pectoralScale: 0.84,
    headTaper: 1,
    scale: 1,
  }),
  fish_species_d2: Object.freeze({
    id: 'fish_species_d2',
    displayName: 'Jaw Hunter Fish',
    sourceSelectionLabel: 'D2',
    sourceExpoPrimitiveId: 'K_expo_fish_D2_jaw_hunter',
    sourceItemId: 'jawHunterFish',
    sourceVariant: 'jawHunterFish',
    constructionTemplate: 'single-reusable-symmetrical-volumetric-template',
    bodyGeometryStyle: 'closedEllipsoidBody',
    bodyMaterial: 'fishScaleMottledDark',
    finMaterial: 'fishFinDark',
    eyeMaterial: 'tinyBlackEye',
    bodyLength: 1.85,
    bodyHeight: 0.4,
    bodyWidth: 0.3,
    tailScale: 1.08,
    dorsalScale: 0.92,
    pectoralScale: 0.82,
    headTaper: 0.9,
    scale: 1,
  }),
  fish_species_d3: Object.freeze({
    id: 'fish_species_d3',
    displayName: 'Sacred Glow Fish',
    sourceSelectionLabel: 'D3',
    sourceExpoPrimitiveId: 'K_expo_fish_D3_sacred_glow',
    sourceItemId: 'sacredGlowFish',
    sourceVariant: 'sacredGlowFish',
    constructionTemplate: 'single-reusable-symmetrical-volumetric-template',
    bodyGeometryStyle: 'closedEllipsoidBody',
    bodyMaterial: 'fishScaleIridescentTeal',
    finMaterial: 'fishFinSpottedTeal',
    eyeMaterial: 'tinyBlackEye',
    bodyLength: 1.55,
    bodyHeight: 0.34,
    bodyWidth: 0.25,
    tailScale: 1.0,
    dorsalScale: 0.88,
    pectoralScale: 0.82,
    headTaper: 1,
    glow: true,
    scale: 1,
  }),
});

export const FISH_SPECIES = Object.freeze(Object.values(FISH_SPECIES_REGISTRY));

export function getFishSpeciesById(speciesId) {
  return FISH_SPECIES_REGISTRY[speciesId] ?? null;
}
