export const AUDIO_CUE_MANIFEST = Object.freeze({
  audio_ch1_folsom_shed_growth_tension_loop: {
    path: '/audio/growth/audio_ch1_folsom_shed_growth_tension_loop.wav',
    category: 'growth',
    loop: true,
    spatial: true,
    volume: 0.72,
    maxDistance: 13,
  },
  audio_ch1_folsom_shed_growth_knife_first_bite_oneshot: {
    path: '/audio/growth/audio_ch1_folsom_shed_growth_knife_first_bite_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 0.95,
    pitchVariation: 0.025,
    volumeVariation: 0.08,
    maxDistance: 15,
  },
  audio_ch1_folsom_shed_growth_knife_second_damage_oneshot: {
    path: '/audio/growth/audio_ch1_folsom_shed_growth_knife_second_damage_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    pitchVariation: 0.02,
    volumeVariation: 0.06,
    maxDistance: 15,
  },
  audio_ch1_folsom_shed_growth_knife_final_clear_oneshot: {
    path: '/audio/growth/audio_ch1_folsom_shed_growth_knife_final_clear_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    maxDistance: 18,
  },
  audio_ch1_folsom_shed_door_open_oneshot: {
    path: '/audio/transitions/audio_ch1_folsom_shed_door_open_oneshot.wav',
    category: 'machinery',
    spatial: true,
    volume: 1,
    maxDistance: 18,
  },
  audio_ch1_folsom_shed_wood_axe_pickup_oneshot: {
    path: '/audio/pickups/audio_ch1_folsom_shed_wood_axe_pickup_oneshot.wav',
    category: 'tools',
    spatial: false,
    volume: 0.86,
  },
  audio_ch1_folsom_shed_torch_pickup_oneshot: {
    path: '/audio/pickups/audio_ch1_folsom_shed_torch_pickup_oneshot.wav',
    category: 'tools',
    spatial: false,
    volume: 0.86,
  },
  audio_ch2_shrine_side_room_seal_knife_cords_cut_oneshot: {
    path: '/audio/growth/audio_ch2_shrine_side_room_seal_knife_cords_cut_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    maxDistance: 14,
  },
  audio_ch2_shrine_side_room_seal_axe_knot_crack_oneshot: {
    path: '/audio/growth/audio_ch2_shrine_side_room_seal_axe_knot_crack_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    maxDistance: 15,
  },
  audio_ch2_keepers_lantern_pickup_reveal_oneshot: {
    path: '/audio/lantern/audio_ch2_keepers_lantern_pickup_reveal_oneshot.wav',
    category: 'tools',
    spatial: false,
    volume: 0.88,
  },
  audio_ch2_keepers_lantern_network_reveal_oneshot: {
    path: '/audio/lantern/audio_ch2_keepers_lantern_network_reveal_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 0.92,
    maxDistance: 20,
  },
  audio_ch2_shrine_crawlspace_panel_open_oneshot: {
    path: '/audio/transitions/audio_ch2_shrine_crawlspace_panel_open_oneshot.wav',
    category: 'machinery',
    spatial: true,
    volume: 1,
    maxDistance: 14,
  },
  audio_ch2_surface_anchor_clear_oneshot: {
    path: '/audio/growth/audio_ch2_surface_anchor_clear_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    pitchVariation: 0.018,
    volumeVariation: 0.06,
    maxDistance: 16,
  },
  audio_ch2_underworks_gate_ambient_tension_stinger_oneshot: {
    path: '/audio/growth/audio_ch2_underworks_gate_ambient_tension_stinger_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 0.78,
    maxDistance: 22,
  },
  audio_ch2_underworks_gate_unseal_oneshot: {
    path: '/audio/transitions/audio_ch2_underworks_gate_unseal_oneshot.wav',
    category: 'machinery',
    spatial: true,
    volume: 1,
    maxDistance: 24,
  },
  audio_ch2_beneath_folsom_entry_stinger_oneshot: {
    path: '/audio/transitions/audio_ch2_beneath_folsom_entry_stinger_oneshot.wav',
    category: 'ambience',
    spatial: false,
    volume: 0.9,
  },
  audio_ch2_beneath_folsom_iron_drain_bar_pickup_oneshot: {
    path: '/audio/pickups/audio_ch2_beneath_folsom_iron_drain_bar_pickup_oneshot.wav',
    category: 'tools',
    spatial: false,
    volume: 0.9,
  },
  audio_ch2_beneath_folsom_drain_grate_bar_socket_oneshot: {
    path: '/audio/prybar/audio_ch2_beneath_folsom_drain_grate_bar_socket_oneshot.wav',
    category: 'prybar',
    spatial: true,
    volume: 0.95,
    maxDistance: 12,
  },
  audio_ch2_beneath_folsom_drain_grate_pry_open_oneshot: {
    path: '/audio/prybar/audio_ch2_beneath_folsom_drain_grate_pry_open_oneshot.wav',
    category: 'prybar',
    spatial: true,
    volume: 1,
    maxDistance: 18,
  },
  audio_ch2_beneath_folsom_hidden_growth_gate_axe_hit_01_oneshot: {
    path: '/audio/growth/audio_ch2_beneath_folsom_hidden_growth_gate_axe_hit_01_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 0.96,
    pitchVariation: 0.018,
    volumeVariation: 0.06,
    maxDistance: 16,
  },
  audio_ch2_beneath_folsom_hidden_growth_gate_axe_hit_02_oneshot: {
    path: '/audio/growth/audio_ch2_beneath_folsom_hidden_growth_gate_axe_hit_02_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 0.98,
    pitchVariation: 0.018,
    volumeVariation: 0.06,
    maxDistance: 16,
  },
  audio_ch2_beneath_folsom_hidden_growth_gate_collapse_oneshot: {
    path: '/audio/growth/audio_ch2_beneath_folsom_hidden_growth_gate_collapse_oneshot.wav',
    category: 'growth',
    spatial: true,
    volume: 1,
    maxDistance: 20,
  },
  audio_ch2_blue_flame_hall_ambience_loop: {
    path: '/audio/ambience/audio_ch2_blue_flame_hall_ambience_loop.wav',
    category: 'ambience',
    loop: true,
    spatial: true,
    volume: 0.62,
    maxDistance: 24,
  },
  audio_ch2_blue_flame_hall_ambience_layer_a_loop: {
    path: '/audio/ambience/audio_ch2_blue_flame_hall_ambience_layer_a_loop.wav',
    category: 'ambience',
    loop: true,
    spatial: true,
    volume: 0.32,
    maxDistance: 18,
  },
  audio_ch2_blue_flame_hall_ambience_layer_b_loop: {
    path: '/audio/ambience/audio_ch2_blue_flame_hall_ambience_layer_b_loop.wav',
    category: 'ambience',
    loop: true,
    spatial: true,
    volume: 0.28,
    maxDistance: 18,
  },
  audio_ch2_lower_shrine_hatch_final_pry_oneshot: {
    path: '/audio/prybar/audio_ch2_lower_shrine_hatch_final_pry_oneshot.wav',
    category: 'prybar',
    spatial: true,
    volume: 1,
    maxDistance: 20,
  },
  audio_ch2_lower_shrine_landing_ambience_loop: {
    path: '/audio/ambience/audio_ch2_lower_shrine_landing_ambience_loop.wav',
    category: 'ambience',
    loop: true,
    spatial: false,
    volume: 0.58,
  },
  audio_ch2_lower_shrine_landing_reveal_stinger_oneshot: {
    path: '/audio/transitions/audio_ch2_lower_shrine_landing_reveal_stinger_oneshot.wav',
    category: 'ambience',
    spatial: false,
    volume: 0.82,
  },
  audio_system_footsteps_grass_walk_loop: {
    path: '/audio/footsteps/audio_system_footsteps_grass_walk_loop.wav',
    category: 'footsteps',
    loop: true,
    spatial: false,
    volume: 0.42,
  },
  audio_system_footsteps_temple_stone_walk_loop: {
    path: '/audio/footsteps/audio_system_footsteps_temple_stone_walk_loop.wav',
    category: 'footsteps',
    loop: true,
    spatial: false,
    volume: 0.42,
  },
});

export const AUDIO_CUE_IDS = Object.freeze(Object.keys(AUDIO_CUE_MANIFEST));

export function getAudioCue(cueId) {
  return AUDIO_CUE_MANIFEST[cueId] ?? null;
}
