import * as THREE from 'three';
import { loadDungeonModel } from '../ModelLoader.js';
import { BROADSWORD_ITEM_ID, BROADSWORD_MODEL_URL, BROADSWORD_VIEW } from './BroadswordTuning.js';
const screenPoint = new THREE.Vector3(); const worldPoint = new THREE.Vector3(); const tmpBox = new THREE.Box3();
export class BroadswordView {
  constructor({ camera, equipmentRuntime } = {}) { this.camera = camera; this.equipmentRuntime = equipmentRuntime; this.root = new THREE.Group(); this.root.name = 'first-person-broadsword-A1-camera-local-root'; this.root.visible = false; this.root.position.set(BROADSWORD_VIEW.restPosition.x, BROADSWORD_VIEW.restPosition.y, BROADSWORD_VIEW.restPosition.z); this.root.rotation.set(BROADSWORD_VIEW.restRotation.x, BROADSWORD_VIEW.restRotation.y, BROADSWORD_VIEW.restRotation.z); this.normalization = new THREE.Group(); this.normalization.name = 'broadsword-ritual-01-normalization-tuning-group'; this.normalization.rotation.set(BROADSWORD_VIEW.modelRotation.x, BROADSWORD_VIEW.modelRotation.y, BROADSWORD_VIEW.modelRotation.z); this.root.add(this.normalization); this.camera.add(this.root); this.pose = { x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 }; this.gestureState = { active: false, dx: 0, dy: 0 }; this.attack = { phase: 'idle', type: 'slash', elapsed: 0 }; this.debug = { equipped: false, loaded: false, attackPhase: 'idle', attackType: 'slash', gestureActive: false, modelUrl: BROADSWORD_MODEL_URL }; this.loadModel(); }
  isEquipped() { return this.equipmentRuntime?.getEquippedWeaponProfile?.().id === BROADSWORD_ITEM_ID; }
  setGestureState(state = {}) { this.gestureState = { ...this.gestureState, ...state }; }
  triggerAttack(type = 'slash') { this.attack = { phase: 'swing', type, elapsed: 0 }; }
  async loadModel() { try { const { root } = await loadDungeonModel({ url: BROADSWORD_MODEL_URL, targetHeight: BROADSWORD_VIEW.targetHeight, maxWidth: BROADSWORD_VIEW.maxWidth, scaleMultiplier: BROADSWORD_VIEW.scale }); root.name = 'weapon_broadsword_ritual_01_glb'; root.traverse((child) => { if (child.isMesh) { child.castShadow = false; child.receiveShadow = false; } }); this.normalization.add(root); this.debug.loaded = true; } catch (error) { console.warn('[Dread Stone Black] Failed to load Broadsword A1 GLB.', error); } }
  getProjectedCenter(viewport) { if (!this.isEquipped() || !this.root.visible || !viewport) return null; this.camera.updateMatrixWorld(); this.root.updateMatrixWorld(true); tmpBox.setFromObject(this.normalization); const point = tmpBox.isEmpty() ? this.root.getWorldPosition(worldPoint) : tmpBox.getCenter(worldPoint); screenPoint.copy(point).project(this.camera); if (screenPoint.z < -1 || screenPoint.z > 1) return this.getFallbackZone(viewport); const rect = viewport.getBoundingClientRect(); return { x: (screenPoint.x * 0.5 + 0.5) * rect.width + rect.left, y: (-screenPoint.y * 0.5 + 0.5) * rect.height + rect.top, radius: 86, projected: true }; }
  getFallbackZone(viewport) { const rect = viewport.getBoundingClientRect(); return { x: rect.left + rect.width * 0.68, y: rect.top + rect.height * 0.66, radius: 112, fallback: true }; }
  projectGestureHit(clientX, clientY, viewport, radius = 86) { const zones = [this.getProjectedCenter(viewport), this.getFallbackZone(viewport)].filter(Boolean); let best = null; for (const zone of zones) { const activeRadius = zone.projected ? radius : zone.radius; const distance = Math.hypot(clientX - zone.x, clientY - zone.y); if (distance <= activeRadius && (!best || distance < best.distance)) best = { ...zone, radius: activeRadius, distance }; } return best; }
  update(deltaSeconds) { const equipped = this.isEquipped(); this.root.visible = equipped; this.debug.equipped = equipped; if (!equipped) return; const dt = Math.max(0.001, Math.min(0.05, deltaSeconds)); const active = this.gestureState.active === true; const dx = THREE.MathUtils.clamp((this.gestureState.dx ?? 0) * BROADSWORD_VIEW.dragPositionScale, -BROADSWORD_VIEW.maxVisualOffset, BROADSWORD_VIEW.maxVisualOffset); const dy = THREE.MathUtils.clamp((this.gestureState.dy ?? 0) * BROADSWORD_VIEW.dragPositionScale, -BROADSWORD_VIEW.maxVisualOffset, BROADSWORD_VIEW.maxVisualOffset); let tx = active ? dx : 0; let ty = active ? -dy : 0; let tz = 0; let trx = active ? THREE.MathUtils.clamp(-(this.gestureState.dy ?? 0) * BROADSWORD_VIEW.dragRotationScale, -BROADSWORD_VIEW.maxVisualRotation, BROADSWORD_VIEW.maxVisualRotation) : 0; let tryy = active ? THREE.MathUtils.clamp((this.gestureState.dx ?? 0) * BROADSWORD_VIEW.dragRotationScale * 0.55, -0.34, 0.34) : 0; let trz = active ? THREE.MathUtils.clamp((this.gestureState.dx ?? 0) * BROADSWORD_VIEW.dragRotationScale, -BROADSWORD_VIEW.maxVisualRotation, BROADSWORD_VIEW.maxVisualRotation) : 0; if (this.attack.phase !== 'idle') { this.attack.elapsed += dt; const duration = this.attack.phase === 'swing' ? 0.22 : 0.34; const p = THREE.MathUtils.clamp(this.attack.elapsed / duration, 0, 1); const s = Math.sin(p * Math.PI); const thrust = this.attack.type === 'thrust'; tx += thrust ? BROADSWORD_VIEW.thrustSwingPosition.x * s : -0.06 * s; ty += thrust ? BROADSWORD_VIEW.thrustSwingPosition.y * s : 0.08 * s; tz += thrust ? BROADSWORD_VIEW.thrustSwingPosition.z * s : -0.08 * s; trx += (thrust ? BROADSWORD_VIEW.thrustSwingRotation.x : BROADSWORD_VIEW.slashSwingRotation.x) * s; tryy += (thrust ? BROADSWORD_VIEW.thrustSwingRotation.y : BROADSWORD_VIEW.slashSwingRotation.y) * s; trz += (thrust ? BROADSWORD_VIEW.thrustSwingRotation.z : BROADSWORD_VIEW.slashSwingRotation.z) * s; if (p >= 1) this.attack = this.attack.phase === 'swing' ? { ...this.attack, phase: 'recovery', elapsed: 0 } : { phase: 'idle', type: this.attack.type, elapsed: 0 }; } const targets = { x: tx, y: ty, z: tz, rx: trx, ry: tryy, rz: trz }; const alpha = 1 - Math.exp(-(active ? BROADSWORD_VIEW.springLag : BROADSWORD_VIEW.settleSpeed) * dt); Object.keys(this.pose).forEach((k) => { this.pose[k] = THREE.MathUtils.lerp(this.pose[k], targets[k], alpha); }); const t = performance.now() / 1000; this.root.position.set(BROADSWORD_VIEW.restPosition.x + this.pose.x, BROADSWORD_VIEW.restPosition.y + this.pose.y + Math.sin(t * 1.7) * BROADSWORD_VIEW.idleBobScale, BROADSWORD_VIEW.restPosition.z + this.pose.z); this.root.rotation.set(BROADSWORD_VIEW.restRotation.x + this.pose.rx, BROADSWORD_VIEW.restRotation.y + this.pose.ry, BROADSWORD_VIEW.restRotation.z + this.pose.rz); this.debug.gestureActive = active; this.debug.attackPhase = this.attack.phase; this.debug.attackType = this.attack.type; }
}
