export const neckManGoreProfile = Object.freeze({
  id: 'neck_man',
  bloodColor: 0x1a0005,
  bloodSecondaryColor: 0x040001,
  particleOpacity: 0.72,
  mistOpacity: 0.36,
  hitParticleCount: 14,
  heavyParticleCount: 24,
  particleBurstType: 'droplet',
  heavyBurstType: 'mist',
  sprayStrength: 1.35,
  decalType: 'slash',
  wallDecalType: 'slash',
  woundType: 'slash',
  woundColor: 0x090003,
  woundScale: 0.5,
  hitDecalScale: [0.32, 0.7],
  wallDecalScale: [0.7, 1.35],
  deathPoolScale: [0.82, 1.35],
  deathPoolOpacity: 0.66,
  corpsePersistenceWeight: 0.85,
  tags: Object.freeze(['pale_black_wound_overlay', 'narrow_sprays', 'long_slash_smears']),
});

