export const sheepDemonGoreProfile = Object.freeze({
  id: 'sheep_demon',
  bloodColor: 0x260006,
  bloodSecondaryColor: 0x050000,
  particleOpacity: 0.82,
  mistOpacity: 0.45,
  hitParticleCount: 22,
  heavyParticleCount: 38,
  particleBurstType: 'droplet',
  heavyBurstType: 'chunky',
  sprayStrength: 1.18,
  decalType: 'splat',
  wallDecalType: 'spray',
  woundType: 'slash',
  woundColor: 0x160004,
  woundScale: 0.72,
  hitDecalScale: [0.42, 0.9],
  wallDecalScale: [0.6, 1.25],
  deathPoolScale: [1.35, 2.15],
  deathPoolOpacity: 0.78,
  corpsePersistenceWeight: 1.25,
  tags: Object.freeze(['fur_wound_overlay', 'chunky_flecks']),
});

