export const weaponGoreProfiles = Object.freeze({
  unarmed: Object.freeze({
    id: 'unarmed',
    particleBurstType: 'droplet',
    hitParticleCount: 10,
    heavyParticleCount: 18,
    sprayStrength: 0.72,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'puncture',
    hitDecalScale: [0.24, 0.48],
    deathPoolScale: [0.88, 1.2],
  }),
  sword: Object.freeze({
    id: 'sword',
    particleBurstType: 'droplet',
    heavyBurstType: 'chunky',
    hitParticleCount: 18,
    heavyParticleCount: 32,
    sprayStrength: 1.22,
    decalType: 'slash',
    wallDecalType: 'slash',
    woundType: 'slash',
    hitDecalScale: [0.44, 0.86],
    wallDecalScale: [0.62, 1.15],
    deathPoolScale: [1.1, 1.74],
  }),
  claw: Object.freeze({
    id: 'claw',
    particleBurstType: 'droplet',
    heavyBurstType: 'chunky',
    hitParticleCount: 16,
    heavyParticleCount: 26,
    sprayStrength: 1.08,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'slash',
    hitDecalScale: [0.34, 0.72],
  }),
  blunt: Object.freeze({
    id: 'blunt',
    particleBurstType: 'mist',
    heavyBurstType: 'chunky',
    hitParticleCount: 12,
    heavyParticleCount: 24,
    sprayStrength: 0.58,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'leak',
    deathPoolScale: [0.9, 1.45],
  }),
  occult: Object.freeze({
    id: 'occult',
    particleBurstType: 'vapor',
    heavyBurstType: 'vapor',
    hitParticleCount: 20,
    heavyParticleCount: 34,
    sprayStrength: 0.84,
    bloodColor: 0x12000a,
    bloodSecondaryColor: 0x030004,
    decalType: 'smear',
    wallDecalType: 'spray',
    woundType: 'leak',
    mistOpacity: 0.52,
  }),
});

