export const weaponGoreProfiles = Object.freeze({
  unarmed: Object.freeze({
    id: 'unarmed',
    bloodColor: 0xb00016,
    freshBloodColor: 0xb00016,
    wetHighlightColor: 0xe02028,
    particleBurstType: 'droplet',
    hitParticleCount: 11,
    heavyParticleCount: 18,
    sprayStrength: 0.76,
    particleOpacity: 0.88,
    hitParticleOpacity: 0.88,
    dropletGravity: 3.7,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'puncture',
    hitDecalScale: [0.3, 0.58],
    wallDecalScale: [0.48, 0.86],
  }),
  sword: Object.freeze({
    id: 'sword',
    bloodColor: 0xc91520,
    freshBloodColor: 0xc91520,
    wetHighlightColor: 0xe02028,
    particleBurstType: 'droplet',
    heavyBurstType: 'chunky',
    hitParticleCount: 18,
    heavyParticleCount: 32,
    sprayStrength: 1.32,
    particleOpacity: 0.94,
    hitParticleOpacity: 0.94,
    streakParticleChance: 0.38,
    brightDropletChance: 0.2,
    dropletGravity: 3.85,
    decalType: 'slash',
    wallDecalType: 'slash',
    woundType: 'slash',
    hitDecalScale: [0.58, 1.05],
    wallDecalScale: [0.78, 1.38],
  }),
  claw: Object.freeze({
    id: 'claw',
    bloodColor: 0xb00016,
    freshBloodColor: 0xb00016,
    wetHighlightColor: 0xe02028,
    particleBurstType: 'droplet',
    heavyBurstType: 'chunky',
    hitParticleCount: 17,
    heavyParticleCount: 27,
    sprayStrength: 1.18,
    particleOpacity: 0.9,
    hitParticleOpacity: 0.9,
    streakParticleChance: 0.32,
    dropletGravity: 3.8,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'slash',
    hitDecalScale: [0.42, 0.82],
    wallDecalScale: [0.64, 1.16],
  }),
  blunt: Object.freeze({
    id: 'blunt',
    bloodColor: 0xb00016,
    freshBloodColor: 0xb00016,
    pooledBloodColor: 0x65000b,
    particleBurstType: 'chunky',
    heavyBurstType: 'chunky',
    hitParticleCount: 13,
    heavyParticleCount: 25,
    sprayStrength: 0.64,
    particleOpacity: 0.92,
    hitParticleOpacity: 0.92,
    streakParticleChance: 0.14,
    dropletGravity: 4.05,
    decalType: 'splat',
    wallDecalType: 'spray',
    woundType: 'leak',
    hitDecalScale: [0.48, 0.94],
  }),
  occult: Object.freeze({
    id: 'occult',
    particleBurstType: 'vapor',
    heavyBurstType: 'vapor',
    hitParticleCount: 20,
    heavyParticleCount: 34,
    sprayStrength: 0.84,
    bloodColor: 0x12000a,
    freshBloodColor: 0x12000a,
    wetHighlightColor: 0x4f001c,
    bloodSecondaryColor: 0x030004,
    pooledBloodColor: 0x210006,
    driedBloodColor: 0x030004,
    decalType: 'smear',
    wallDecalType: 'spray',
    woundType: 'leak',
    particleOpacity: 0.62,
    hitParticleOpacity: 0.62,
    mistOpacity: 0.52,
    dropletGravity: 1.85,
    streakParticleChance: 0.06,
  }),
});
