const PINE_SIZE_BANDS = Object.freeze([
  ['tiny', { height: 3.2, width: 1.8, weight: 0.9, scaleJitter: 0.14, sinkIntoGround: 0.05 }],
  ['small', { height: 4.4, width: 2.4, weight: 1.2, scaleJitter: 0.13, sinkIntoGround: 0.06 }],
  ['medium', { height: 5.8, width: 3.0, weight: 1.4, scaleJitter: 0.12, sinkIntoGround: 0.07 }],
  ['tall', { height: 7.2, width: 3.6, weight: 1.25, scaleJitter: 0.11, sinkIntoGround: 0.08 }],
  ['large', { height: 8.8, width: 4.3, weight: 1.0, scaleJitter: 0.1, sinkIntoGround: 0.09 }],
  ['giant', { height: 10.5, width: 5.0, weight: 0.55, scaleJitter: 0.09, sinkIntoGround: 0.1 }],
  ['ancient', { height: 12.5, width: 5.8, weight: 0.35, scaleJitter: 0.08, sinkIntoGround: 0.12 }],
]);
export const FOLSOM_PINE_SOURCE_SPRITES = Object.freeze(['./assets/sprites/foliage/pine_tree_broad_01.png','./assets/sprites/foliage/pine_tree_large_01.png','./assets/sprites/foliage/pine_tree_large_02.png','./assets/sprites/foliage/pine_tree_small_01.png','./assets/sprites/foliage/pine_tree_tall_01.png','./assets/sprites/foliage/pine_tree_tall_02.png']);
export const FOLSOM_PINE_MAX_BILLBOARD_YAW_OFFSET = 0.12;
export const FOLSOM_PINE_SPRITE_BASELINES = Object.freeze({
  './assets/sprites/foliage/pine_tree_broad_01.png': Object.freeze({ bottomTransparentPaddingRatio: 0.0273 }),
  './assets/sprites/foliage/pine_tree_large_01.png': Object.freeze({ bottomTransparentPaddingRatio: 0.0293 }),
  './assets/sprites/foliage/pine_tree_large_02.png': Object.freeze({ bottomTransparentPaddingRatio: 0.0293 }),
  './assets/sprites/foliage/pine_tree_small_01.png': Object.freeze({ bottomTransparentPaddingRatio: 0.1289 }),
  './assets/sprites/foliage/pine_tree_tall_01.png': Object.freeze({ bottomTransparentPaddingRatio: 0.0586 }),
  './assets/sprites/foliage/pine_tree_tall_02.png': Object.freeze({ bottomTransparentPaddingRatio: 0.0156 }),
});
function seededRandom(seed) { let state = seed >>> 0; return () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 4294967296; }; }
function chooseWeighted(items, random) { const total = items.reduce((sum, item) => sum + (item.weight ?? 1), 0); let cursor = random() * total; for (const item of items) { cursor -= item.weight ?? 1; if (cursor <= 0) return item; } return items.at(-1); }
function inZone(point, zone) { const [x, z] = point; if (zone.radius) return Math.hypot(x - zone.center[0], z - zone.center[1]) <= zone.radius; if (zone.radiusX && zone.radiusZ) return (((x - zone.center[0]) ** 2) / (zone.radiusX ** 2)) + (((z - zone.center[1]) ** 2) / (zone.radiusZ ** 2)) <= 1; if (zone.minX !== undefined) return x >= zone.minX && x <= zone.maxX && z >= zone.minZ && z <= zone.maxZ; return false; }
export function createPineBillboardVariants({ spritePaths = FOLSOM_PINE_SOURCE_SPRITES, sizeBands = PINE_SIZE_BANDS } = {}) { if (spritePaths.length !== 6) throw new Error(`Folsom invalid: expected six pine source sprites, found ${spritePaths.length}.`); return Object.freeze(spritePaths.flatMap((path, spriteIndex) => sizeBands.map(([band, metrics]) => Object.freeze({ id: `pine${String(spriteIndex + 1).padStart(2, '0')}_${band}`, sourceSpriteId: `pine${String(spriteIndex + 1).padStart(2, '0')}`, path, band, type: 'pine-billboard', height: metrics.height, width: metrics.width, scaleJitter: metrics.scaleJitter, yawJitter: FOLSOM_PINE_MAX_BILLBOARD_YAW_OFFSET, bottomTransparentPaddingRatio: FOLSOM_PINE_SPRITE_BASELINES[path]?.bottomTransparentPaddingRatio ?? 0, sinkIntoGround: metrics.sinkIntoGround, weight: metrics.weight })))); }
export function createPineForestSwathe({ idPrefix, center, radiusX, radiusZ, count, seed = 1, variants, variantWeights = {}, avoidZones = [], terrainSampler, tags = [] }) { const random = seededRandom(seed); const weighted = variants.map((variant) => ({ ...variant, weight: variantWeights[variant.band] ?? variant.weight ?? 1 })); const placements = []; let attempts = 0; while (placements.length < count && attempts < count * 80) { attempts += 1; const angle = random() * Math.PI * 2; const radius = Math.sqrt(random()); const x = center[0] + Math.cos(angle) * radiusX * radius; const z = center[1] + Math.sin(angle) * radiusZ * radius; if (avoidZones.some((zone) => inZone([x, z], zone))) continue; const variant = chooseWeighted(weighted, random); const jitter = 1 + (random() * 2 - 1) * variant.scaleJitter; placements.push(Object.freeze({ id: `${idPrefix}_${String(placements.length + 1).padStart(3, '0')}`, variantId: variant.id, spritePath: variant.path, position: [Number(x.toFixed(3)), Number((terrainSampler?.sampleOutdoorY?.(x, z) ?? 0).toFixed(3)), Number(z.toFixed(3))], height: Number((variant.height * jitter).toFixed(3)), width: Number((variant.width * jitter).toFixed(3)), yawOffset: Number(((random() * 2 - 1) * Math.min(variant.yawJitter ?? 0, FOLSOM_PINE_MAX_BILLBOARD_YAW_OFFSET)).toFixed(3)), bottomTransparentPaddingRatio: variant.bottomTransparentPaddingRatio ?? 0, sinkIntoGround: variant.sinkIntoGround, tags: ['pine-billboard', ...tags] })); } return Object.freeze(placements); }
