import * as THREE from 'three';

function material(key, options, fallback) { const profile = options.textures?.[key] ?? fallback; return options.makeMaterial?.(profile, { materialKey: key, profile, usedFallback: !options.textures?.[key] }) ?? new THREE.MeshStandardMaterial({ color: profile.color, roughness: profile.roughness ?? 0.95, metalness: profile.metalness ?? 0 }); }
function addBox(group, id, size, position, mat, rotation = [0, 0, 0]) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(...size), mat); mesh.name = id; mesh.position.set(...position); mesh.rotation.set(...rotation); mesh.castShadow = true; mesh.receiveShadow = true; group.add(mesh); return mesh; }
function addStone(group, id, radius, position, mat) { const mesh = new THREE.Mesh(new THREE.DodecahedronGeometry(radius, 0), mat); mesh.name = id; mesh.position.set(...position); mesh.scale.y = 0.62; mesh.rotation.set(0.2, radius * 2.1, 0.1); mesh.receiveShadow = true; group.add(mesh); return mesh; }

function campGroup(definition, options) {
  const group = new THREE.Group(); group.name = `OutdoorCampKit-${definition.id}`;
  const [x, z] = definition.center; const y = options.terrainSampler.sampleOutdoorY(x, z); const wood = material('agedWood', options, { color: 0x65503b, roughness: 0.97 }); const stone = material('stoneOutcrop', options, { color: 0x6d6a62, roughness: 0.99 }); const cloth = material('prayerCloth', options, { color: 0x8b806f, roughness: 1 });
  for (let index = 0; index < 9; index += 1) { const angle = (index / 9) * Math.PI * 2; addStone(group, `${definition.id}-dead-fire-ring-${index}`, 0.28, [x + Math.cos(angle) * 1.25, y + 0.16, z + Math.sin(angle) * 1.25], stone); }
  addBox(group, `${definition.id}-shelter-back-beam`, [0.28, 3.2, 0.28], [x - 4, y + 1.6, z + 2.5], wood, [0, 0, -0.08]); addBox(group, `${definition.id}-shelter-front-beam`, [0.28, 2.3, 0.28], [x + 1.5, y + 1.15, z + 2.5], wood, [0, 0, 0.08]);
  addBox(group, `${definition.id}-shelter-roof`, [6.1, 0.18, 3.7], [x - 1.25, y + 3.05, z + 2.5], wood, [0, 0, -0.14]);
  addBox(group, `${definition.id}-bedroll`, [2.2, 0.18, 0.9], [x - 1.8, y + 0.12, z + 2.1], cloth, [0, 0.25, 0]);
  addBox(group, `${definition.id}-clue-surface`, [1.8, 1.2, 0.18], [definition.cluePosition[0], y + 1.4, definition.cluePosition[1]], wood, [0, definition.clueYaw ?? 0, 0]);
  if (definition.style === 'hunter') {
    addBox(group, `${definition.id}-skinning-rack-crossbeam`, [4.2, 0.22, 0.22], [x + 4.8, y + 2.7, z - 2.2], wood); [-1, 1].forEach((side) => addBox(group, `${definition.id}-skinning-rack-post-${side}`, [0.24, 3.4, 0.24], [x + 4.8 + side * 1.8, y + 1.7, z - 2.2], wood, [0, 0, side * 0.08]));
    addBox(group, `${definition.id}-broken-deer-stand`, [2.6, 0.22, 2.2], [x - 5.2, y + 2.5, z - 3.5], wood, [0.12, 0.3, -0.1]);
  }
  if (definition.style === 'church') {
    [-4, 0, 4].forEach((offset, index) => { addBox(group, `${definition.id}-prayer-post-${index}`, [0.22, 4.5, 0.22], [x + offset, y + 2.25, z - 3.2], wood); for (let strip = 0; strip < 3; strip += 1) addBox(group, `${definition.id}-prayer-strip-${index}-${strip}`, [0.7, 0.07, 0.16], [x + offset + 0.38, y + 3.4 - strip * 0.45, z - 3.2], cloth, [0, 0, 0.15 * (strip - 1)]); });
    addBox(group, `${definition.id}-devotional-marker`, [1.1, 2.5, 0.7], [x, y + 1.25, z - 0.8], stone);
  }
  if (definition.style === 'scout') {
    addBox(group, `${definition.id}-windbreak`, [5.8, 2.2, 0.28], [x - 1.2, y + 1.1, z + 3.8], wood, [0, -0.28, 0.06]);
    addStone(group, `${definition.id}-lookout-stone`, 2.2, [x + 5.6, y + 1.1, z - 2], stone);
    addBox(group, `${definition.id}-broken-observation-post`, [0.35, 5.1, 0.35], [x - 4.8, y + 2.55, z - 2.8], wood, [0, 0, -0.17]);
  }
  group.userData = { id: definition.id, kind: 'outdoorCampKit', style: definition.style, traversableClearing: true, clueSurfaceId: `${definition.id}-clue-surface`, meshCount: group.children.length, generatedBy: 'OutdoorCampKit' }; return group;
}

function retainingWall(definition, options) { const group = new THREE.Group(); group.name = `OutdoorRetainingWallKit-${definition.id}`; const mat = material(definition.material ?? 'militaryStone', options, { color: 0x77736a, roughness: 0.98 }); definition.points.slice(0, -1).forEach((from, index) => { const to = definition.points[index + 1]; const dx = to[0] - from[0]; const dz = to[1] - from[1]; const length = Math.hypot(dx, dz); const x = (from[0] + to[0]) * 0.5; const z = (from[1] + to[1]) * 0.5; const y = options.terrainSampler.sampleOutdoorY(x, z); addBox(group, `${definition.id}-segment-${index}`, [definition.thickness ?? 1.2, definition.height ?? 2.4, length], [x, y + (definition.height ?? 2.4) * 0.5, z], mat, [0, Math.atan2(dx, dz), 0]); }); group.userData = { id: definition.id, kind: 'retainingWallKit', meshCount: group.children.length }; return group; }

function fortSilhouette(definition, options) { const group = new THREE.Group(); group.name = `OutdoorMilitaryApproachKit-${definition.id}`; const mat = material('militaryStone', options, { color: 0x55534f, roughness: 0.99 }); const [x, z] = definition.center; const y = options.terrainSampler.sampleOutdoorY(x, z); addBox(group, `${definition.id}-wall`, [72, 14, 7], [x, y + 7, z], mat); [-29, 29].forEach((offset, index) => addBox(group, `${definition.id}-tower-${index}`, [12, 24, 12], [x + offset, y + 12, z - 1], mat)); addBox(group, `${definition.id}-closed-gate-left`, [8, 10, 1.2], [x - 5, y + 5, z - 4], mat); addBox(group, `${definition.id}-closed-gate-right`, [8, 10, 1.2], [x + 5, y + 5, z - 4], mat); group.userData = { id: definition.id, kind: 'emptyFortExteriorSilhouette', exteriorOnly: true, accessibleInterior: false, meshCount: group.children.length }; return group; }

function roadMarker(definition, options) { const group = new THREE.Group(); group.name = `OutdoorRoadMarkerKit-${definition.id}`; const mat = material(definition.material ?? 'militaryStone', options, { color: 0x77736a, roughness: 0.98 }); const wood = material('agedWood', options, { color: 0x5f4935, roughness: 0.97 }); const [x, z] = definition.center; const y = options.terrainSampler.sampleOutdoorY(x, z); addBox(group, `${definition.id}-military-post`, [0.55, definition.height ?? 3.5, 0.55], [x, y + (definition.height ?? 3.5) * 0.5, z], definition.wooden ? wood : mat, [0, definition.yaw ?? 0, definition.lean ?? 0]); addStone(group, `${definition.id}-broken-base`, 0.75, [x + 0.65, y + 0.3, z - 0.3], mat); group.userData = { id: definition.id, kind: 'roadMarkerKit', broken: true, meshCount: group.children.length }; return group; }

function boundaryGate(definition, options) { const group = new THREE.Group(); group.name = `OutdoorBoundaryGateKit-${definition.id}`; const stone = material('militaryStone', options, { color: 0x66645e, roughness: 0.99 }); const wood = material('agedWood', options, { color: 0x4f3d2d, roughness: 0.98 }); const metal = material('rustedIron', options, { color: 0x58463a, roughness: 0.9, metalness: 0.25 }); const [x, z] = definition.center; const y = options.terrainSampler.sampleOutdoorY(x, z); [-1, 1].forEach((side) => { addBox(group, `${definition.id}-gate-pier-${side}`, [3.4, 9, 3.4], [x + side * 8.8, y + 4.5, z], stone); const door = addBox(group, `${definition.id}-closed-timber-door-${side}`, [8.2, 7.4, 0.8], [x + side * 4.15, y + 3.7, z - 0.9], wood, [0, side * -0.05, side * 0.04]); for (let band = 0; band < 3; band += 1) addBox(group, `${definition.id}-rusted-door-band-${side}-${band}`, [8.3, 0.22, 0.92], [door.position.x, y + 1.5 + band * 2.1, z - 0.95], metal, [0, side * -0.05, side * 0.04]); }); for (let index = 0; index < 6; index += 1) addStone(group, `${definition.id}-collapsed-approach-stone-${index}`, 0.8 + (index % 3) * 0.28, [x - 6 + index * 2.4, y + 0.45, z - 3.2 + (index % 2) * 1.2], stone); group.userData = { id: definition.id, kind: 'intentionalProductionBoundaryGate', closed: true, visibleJustification: 'ruined military gate and collapse', accessibleInterior: false, meshCount: group.children.length }; return group; }

export function createOutdoorWildernessStructureGroups(definitions = [], options = {}) { return definitions.map((definition) => definition.kind === 'camp' ? campGroup(definition, options) : definition.kind === 'retainingWall' ? retainingWall(definition, options) : definition.kind === 'fortSilhouette' ? fortSilhouette(definition, options) : definition.kind === 'roadMarker' ? roadMarker(definition, options) : definition.kind === 'boundaryGate' ? boundaryGate(definition, options) : null).filter(Boolean); }
