import * as THREE from 'three';

function labelTexture(text) { const canvas = document.createElement('canvas'); canvas.width = 768; canvas.height = 180; const context = canvas.getContext('2d'); context.fillStyle = '#11130f'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#d9dfcf'; context.font = '26px monospace'; text.split('\n').slice(0, 4).forEach((line, index) => context.fillText(line, 18, 38 + index * 36)); const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace; return texture; }

export function createOutdoorMaterialGallery({ profiles = {}, makeMaterial, loadTexture, origin = [-170, -535], maxProfiles = 20 } = {}) {
  if (typeof document === 'undefined') return null;
  const entries = Object.entries(profiles).filter(([, profile]) => profile?.path || profile?.color).slice(0, maxProfiles); const group = new THREE.Group(); group.name = 'OARB-development-outdoor-material-gallery';
  entries.forEach(([key, profile], index) => { const column = index % 5; const row = Math.floor(index / 5); const x = origin[0] + column * 16; const z = origin[1] + row * 20; const texture = profile.path ? loadTexture?.(profile.path) : null; const raw = new THREE.Mesh(new THREE.PlaneGeometry(6, 6), new THREE.MeshBasicMaterial({ map: texture, color: texture ? 0xffffff : profile.color ?? 0xffffff, side: THREE.DoubleSide })); raw.name = `material-gallery-${key}-raw-source`; raw.rotation.x = -Math.PI / 2; raw.position.set(x - 3.4, 0.12, z); const finalMaterial = makeMaterial(profile, { materialKey: key, profile, usedFallback: false }); const final = new THREE.Mesh(new THREE.PlaneGeometry(6, 6), finalMaterial); final.name = `material-gallery-${key}-final-material`; final.rotation.x = -Math.PI / 2; final.position.set(x + 3.4, 0.13, z); const label = new THREE.Mesh(new THREE.PlaneGeometry(13, 3.1), new THREE.MeshBasicMaterial({ map: labelTexture(`${key}\n${profile.path ?? 'procedural-color'}\nrepeat=${JSON.stringify(profile.repeat ?? [1, 1])}\nrough=${profile.roughness ?? 0.9} metal=${profile.metalness ?? 0}`), transparent: false, side: THREE.DoubleSide })); label.name = `material-gallery-${key}-metadata`; label.position.set(x, 2.5, z + 4.5); group.add(raw, final, label); });
  const grid = new THREE.GridHelper(82, 41, 0xffffff, 0x596054); grid.position.set(origin[0] + 32, 0.05, origin[1] + 30); group.add(grid); group.userData = { kind: 'outdoorMaterialGallery', developmentOnly: true, profileCount: entries.length, showsRawAndFinal: true, metadata: ['path', 'repeat', 'roughness', 'metalness', 'color-space'] }; return group;
}
