import * as THREE from 'three';

function line(points, color, closed = false, y = 0.12) { const vertices = points.map(([x, z]) => new THREE.Vector3(x, y, z)); if (closed && vertices.length) vertices.push(vertices[0].clone()); return new THREE.Line(new THREE.BufferGeometry().setFromPoints(vertices), new THREE.LineBasicMaterial({ color, depthTest: true, transparent: true, opacity: 0.9 })); }
function queryDebugTokens() { if (typeof window === 'undefined') return new Set(); return new Set((new URLSearchParams(window.location.search).get('debug') ?? '').split(',').filter(Boolean)); }
export function resolveOutdoorDebugFlags() { const tokens = queryDebugTokens(); const all = tokens.has('outdoors'); return Object.freeze({ terrain: all || tokens.has('terrain') || globalThis.__DSB_TERRAIN_DEBUG__ === true, ponds: all || tokens.has('ponds') || globalThis.__DSB_POND_DEBUG__ === true, fishing: all || tokens.has('fishing') || globalThis.__DSB_FISHING_DEBUG__ === true, foliage: all || tokens.has('foliage') || tokens.has('forest-stamps') || globalThis.__DSB_FOLIAGE_DEBUG__ === true, forestStamps:all||tokens.has('forest-stamps'), route: all || tokens.has('route') || globalThis.__DSB_ROUTE_DEBUG__ === true, gallery: tokens.has('outdoor-material-gallery') || globalThis.__DSB_OUTDOOR_MATERIAL_GALLERY__ === true }); }

export function createOutdoorWorldDebugGroup(definition, runtime, flags) {
  if (!flags || !Object.values(flags).some(Boolean)) return null;
  const group = new THREE.Group(); group.name = 'OARB-development-outdoor-debug-overlays'; group.userData = { developmentOnly: true, flags };
  if (flags.terrain) (runtime.debug?.terrainChunkSummaries ?? []).forEach((summary) => { const { minX, maxX, minZ, maxZ } = summary.bounds; const y = summary.maximumElevation + 0.18; const outline = line([[minX, minZ], [maxX, minZ], [maxX, maxZ], [minX, maxZ]], summary.maximumSlope > 0.65 ? 0xff3333 : 0xffff33, true, y); outline.name = `terrain-debug-${summary.id}`; outline.userData = summary; group.add(outline); });
  if (flags.ponds) (definition.waterBodies ?? []).forEach((body) => { const heights = body.footprint?.layerHeights ?? {}; [['waterOutline', 0x22aaff, heights.waterY], ['mudBedOutline', 0xffaa22, heights.mudBedY], ['outerShoreOutline', 0x33ff66, heights.wetShoreY]].forEach(([key, color, y]) => { if (body.footprint?.[key]?.length) { const outline = line(body.footprint[key], color, true, y + 0.09); outline.name = `pond-debug-${body.id}-${key}`; group.add(outline); } }); (body.fishingBanks ?? []).forEach((bank) => { const marker = new THREE.Mesh(new THREE.SphereGeometry(0.38, 8, 6), new THREE.MeshBasicMaterial({ color: 0x00ffff, wireframe: true })); marker.position.set(bank.position[0], (runtime.terrainSampler.sampleOutdoorY(...bank.position) ?? 0) + 0.5, bank.position[1]); marker.name = `pond-casting-bank-${bank.id}`; group.add(marker); }); });
  if (flags.fishing) (runtime.fishingZones ?? []).forEach((zone) => { if (zone.points?.length) { const outline = line(zone.points, 0x00ffff, zone.shape === 'polygon', (zone.position?.y ?? 0) + 0.14); outline.name = `fishing-zone-debug-${zone.id}`; outline.userData = { speciesPool: zone.fishSpeciesPool, waterBodyId: zone.waterBodyId }; group.add(outline); } });
  if (flags.foliage) { const accepted = (definition.foliageBillboards ?? []).filter((_, index) => index % 8 === 0); const acceptedGeometry = new THREE.BufferGeometry().setFromPoints(accepted.map((placement) => new THREE.Vector3(placement.position[0], runtime.terrainSampler.sampleOutdoorY(placement.position[0], placement.position[2]) + 0.18, placement.position[2]))); const acceptedPoints = new THREE.Points(acceptedGeometry, new THREE.PointsMaterial({ color: 0x33ff55, size: 0.35 })); acceptedPoints.name = 'foliage-debug-accepted-sample'; group.add(acceptedPoints); const rejected = definition.foliageRejectedPlacements ?? []; if (rejected.length) { const rejectedGeometry = new THREE.BufferGeometry().setFromPoints(rejected.map((candidate) => new THREE.Vector3(candidate.x, runtime.terrainSampler.sampleOutdoorY(candidate.x, candidate.z) + 0.2, candidate.z))); const rejectedPoints = new THREE.Points(rejectedGeometry, new THREE.PointsMaterial({ color: 0xff3333, size: 0.42 })); rejectedPoints.name = 'foliage-debug-rejected-candidates'; group.add(rejectedPoints); } }
  if(flags.forestStamps)(definition.foliageCommunities??[]).forEach(stamp=>{const ellipse=Array.from({length:49},(_,i)=>[stamp.bounds.center[0]+Math.cos(i/48*Math.PI*2)*stamp.bounds.radiusX,stamp.bounds.center[1]+Math.sin(i/48*Math.PI*2)*stamp.bounds.radiusZ]);const boundary=line(ellipse,0x55aaff,true,runtime.terrainSampler.sampleOutdoorY(...stamp.bounds.center)+.3);boundary.name=`forest-stamp-boundary-${stamp.id}`;boundary.userData=stamp;group.add(boundary);[...(stamp.clusterCenters??[]).map(p=>({...p,color:0xffaa22,kind:'cluster'})),...(stamp.glades??[]).map(p=>({...p,color:0x22ffff,kind:'glade'}))].forEach(p=>{const marker=new THREE.Mesh(new THREE.RingGeometry(.7,p.radius??1.2,16),new THREE.MeshBasicMaterial({color:p.color,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.set(p.x,runtime.terrainSampler.sampleOutdoorY(p.x,p.z)+.25,p.z);marker.name=`forest-stamp-${p.kind}-${stamp.id}`;group.add(marker);});});
  if (flags.route) (definition.spawns ?? []).forEach((spawn) => { const marker = new THREE.Mesh(new THREE.ConeGeometry(0.45, 1.3, 6), new THREE.MeshBasicMaterial({ color: spawn.userData?.developmentOnly ? 0xff33ff : 0x33ff66, wireframe: true })); marker.name = `route-spawn-debug-${spawn.id}`; marker.position.set(spawn.position.x, runtime.terrainSampler.sampleOutdoorY(spawn.position.x, spawn.position.z) + 0.65, spawn.position.z); group.add(marker); });
  return group;
}
