import * as THREE from 'three';

export const NECK_MAN_ANIMATION_FILES = Object.freeze({
  idle: './assets/enemies/neck_man/neckman_01_optimized_idle.glb',
  walk: './assets/enemies/neck_man/neckman_01_optimized_walk.glb',
  crawl: './assets/enemies/neck_man/neckman_01_optimized_crawl.glb',
  run: './assets/enemies/neck_man/neckman_01_optimized_run.glb',
  punch_left: './assets/enemies/neck_man/neckman_01_optimized_punch_left.glb',
  punch_right: './assets/enemies/neck_man/neckman_01_optimized_punch_right.glb',
  cross_punch_left: './assets/enemies/neck_man/neckman_01_optimized_cross_punch_left.glb',
  kick_right: './assets/enemies/neck_man/neckman_01_optimized_kick_right.glb',
  talk: './assets/enemies/neck_man/neckman_01_optimized_talk.glb',
  die: './assets/enemies/neck_man/neckman_01_optimized_die.glb',
});

export const NECK_MAN_FACTION_STATE_TO_ANIMATION = Object.freeze({
  spawn: 'idle',
  patrol: 'walk',
  investigate_enemy_faction: 'walk',
  seek_enemy_faction: 'run',
  combat_enter: 'walk',
  combat_circle: 'walk',
  combat_feint: 'walk',
  combat_lunge: 'run',
  attack_enemy_faction: 'punch_right',
  jump_attack_enemy_faction: 'kick_right',
  defensive_backstep: 'walk',
  defensive_strafe: 'walk',
  recover: 'idle',
  seek_player_fallback: 'walk',
  attack_player_fallback: 'punch_left',
  dead: 'die',
});

export const neckManConfig = Object.freeze({
  id: 'neck_man',
  identity: Object.freeze({
    id: 'neck_man',
    displayName: 'Neck Man',
    species: 'neck_man',
    role: 'faction_enemy',
    factionId: 'neck_man',
    opposingFactionId: 'sheep_demon',
    tags: Object.freeze(['enemy', 'black_grass_temple', 'prototype_creature']),
  }),
  assets: Object.freeze({
    basePath: './assets/enemies/neck_man/',
    animationFiles: NECK_MAN_ANIMATION_FILES,
    expectedAnimations: Object.freeze(Object.keys(NECK_MAN_ANIMATION_FILES)),
    fallbackAnimations: Object.freeze({
      attack: 'punch_right',
      jump: 'kick_right',
      special: 'talk',
      dead: 'die',
    }),
    materialMetadata: Object.freeze({
      note: 'Preserve current GLB color and material balance; only texture color spaces are normalized.',
    }),
  }),
  scale: Object.freeze({
    targetHeight: 2.05,
    maxWidth: 1.35,
    groundOffset: 0,
    yOffset: 0,
    rotationOffset: 0,
    scaleMultiplier: 1,
    bodyRadius: 0.54,
  }),
  animationProfile: Object.freeze({
    idle: 'idle',
    walk: 'walk',
    run: 'run',
    attack: 'punch_right',
    jump: 'kick_right',
    die: 'die',
    talk: 'talk',
    special: 'talk',
    factionStateToAnimation: NECK_MAN_FACTION_STATE_TO_ANIMATION,
    fallbackMapping: Object.freeze({
      attack_player_fallback: 'punch_left',
      attack_enemy_faction: 'punch_right',
      jump_attack_enemy_faction: 'kick_right',
      dead: 'die',
    }),
    defaultFadeSeconds: 0.1,
    minimumHoldTimes: Object.freeze({
      patrol: 0.8,
      seek_enemy_faction: 0.7,
    }),
    disabledAnimations: Object.freeze([]),
    rareAnimations: Object.freeze(['crawl']),
    attackAnimationChoices: Object.freeze(['punch_left', 'punch_right', 'cross_punch_left', 'kick_right']),
    oneShotStates: Object.freeze(['punch_left', 'punch_right', 'cross_punch_left', 'kick_right', 'die']),
  }),
  materialProfile: Object.freeze({
    id: 'neck_man_preserve_current_color',
    cloneMaterials: true,
    roughness: null,
    metalness: null,
  }),
  combatProfile: Object.freeze({
    maxHealth: 38,
    attackDamage: 10,
    playerAttackDamage: 15,
    playerAttackRange: 2.75,
    playerAttackArcRadians: THREE.MathUtils.degToRad(72),
    attackRange: 1.9,
    visualContactRange: 1.7,
    attackImpactRange: 1.84,
    attackCommitRange: 2.55,
    attackCooldown: 0.95,
    attackCooldownSeconds: 0.95,
    damageWindow: Object.freeze({ start: 0.34, end: 0.64 }),
    attackDamageWindow: Object.freeze({ start: 0.34, end: 0.64 }),
    lungeDistance: 0.62,
    desiredCombatDistance: 1.92,
    tooCloseDistance: 0.98,
    bodySeparation: 0.92,
    minimumBodySeparation: 0.92,
    jumpAttackChance: 0,
    defensiveManeuverChance: 0.18,
    offensiveLungeChance: 0.58,
    turnSpeed: 5.8,
  }),
  aiProfile: Object.freeze({
    behaviorType: 'faction_combatant',
    detectionRanges: Object.freeze({ combatEngageDistance: 5.9 }),
    targetPriority: Object.freeze(['opposing_faction', 'player_fallback', 'patrol']),
    playerFallbackRules: Object.freeze({ detectionRadius: 13.5, revengeSeconds: 6 }),
    factionPriorityRules: Object.freeze({ opposingFactionId: 'sheep_demon' }),
    navigationPreferences: Object.freeze({ walkSpeed: 0.92, seekSpeed: 1.7, clearanceRadius: 0.58 }),
    patrolBehavior: Object.freeze({ crawl: 'rare/disabled in current faction behavior' }),
    combatManeuverPreferences: Object.freeze({
      jumpAttackChance: 0,
      defensiveManeuverChance: 0.18,
      offensiveLungeChance: 0.58,
    }),
  }),
  spawnProfile: Object.freeze({
    metadataOnly: true,
    placement: 'Black Grass Temple faction-war anchors.',
    initialFactionWave: 1,
    maxActiveFactionCount: 2,
  }),
  debugProfile: Object.freeze({
    showBounds: false,
    showGrounding: false,
    showAttackRange: false,
    showTargetLine: false,
    showCurrentAnimation: true,
    showCurrentState: true,
  }),
});
