export const RAM_MAN_FRIENDLY_ANIMATION_FILES = Object.freeze({
  idle: './assets/npcs/ram_man/ram_man_friendly_idle_01.glb',
  walk: './assets/npcs/ram_man/ram_man_friendly_walk_01.glb',
});

export const ramManFriendlyConfig = Object.freeze({
  id: 'ram_man_friendly',
  identity: Object.freeze({
    id: 'ram_man_friendly',
    displayName: 'Friendly Ram Man',
    species: 'ram_man',
    role: 'npc',
    tags: Object.freeze(['friendly', 'npc', 'south_reliquary_crypt']),
  }),
  assets: Object.freeze({
    basePath: './assets/npcs/ram_man/',
    animationFiles: RAM_MAN_FRIENDLY_ANIMATION_FILES,
    expectedAnimations: Object.freeze(['idle', 'walk']),
    fallbackAnimations: Object.freeze({
      run: 'walk',
      talk: 'idle',
      attack: 'idle',
      die: 'idle',
      special: 'idle',
    }),
  }),
  scale: Object.freeze({
    targetHeight: 1.72,
    maxWidth: 1.15,
    groundOffset: 0,
    yOffset: 0,
    rotationOffset: 0,
    scaleMultiplier: 1,
    bodyRadius: 0.42,
  }),
  animationProfile: Object.freeze({
    idle: 'idle',
    walk: 'walk',
    run: 'walk',
    attack: 'idle',
    jump: 'idle',
    die: 'idle',
    talk: 'idle',
    special: 'idle',
    fallbackMapping: Object.freeze({
      patrol: 'walk',
      dead: 'idle',
    }),
    defaultFadeSeconds: 0.16,
    minimumHoldTimes: Object.freeze({
      idle: 0.25,
      walk: 0.25,
    }),
    disabledAnimations: Object.freeze(['attack', 'jump', 'die']),
    rareAnimations: Object.freeze([]),
    attackAnimationChoices: Object.freeze([]),
  }),
  materialProfile: Object.freeze({
    id: 'ram_man_default_dungeon_materials',
    cloneMaterials: true,
  }),
  combatProfile: Object.freeze({
    maxHealth: 1,
    attackDamage: 0,
    attackRange: 0,
    visualContactRange: 0,
    attackImpactRange: 0,
    attackCooldown: 0,
    damageWindow: Object.freeze({ start: 0, end: 0 }),
    lungeDistance: 0,
    desiredCombatDistance: 0,
    tooCloseDistance: 0,
    bodySeparation: 0,
    jumpAttackChance: 0,
    defensiveManeuverChance: 0,
    offensiveLungeChance: 0,
  }),
  aiProfile: Object.freeze({
    behaviorType: 'friendly_npc',
    detectionRanges: Object.freeze({ interactionRange: 0 }),
    targetPriority: Object.freeze([]),
    playerFallbackRules: Object.freeze({ hostile: false }),
    factionPriorityRules: Object.freeze({ hostile: false }),
    navigationPreferences: Object.freeze({ patrolSpeed: 0.34 }),
    patrolBehavior: Object.freeze({ pauseSeconds: 0.9, route: 'opening chamber ambience loop' }),
    combatManeuverPreferences: Object.freeze({ none: true }),
  }),
  spawnProfile: Object.freeze({
    metadataOnly: true,
    placement: 'R05 guardian chamber around X 0, Z 14, clear of the reliquary route.',
  }),
  debugProfile: Object.freeze({
    showBounds: false,
    showGrounding: false,
    showAttackRange: false,
    showTargetLine: false,
    showCurrentAnimation: true,
    showCurrentState: true,
  }),
});
